# Generated by Django 2.2.6 on 2019-10-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0013_auto_20190723_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crudevent',
            name='object_json_repr',
        ),
    ]
